<p><label for="school">Select the HBCU you attend(ed):</label>
           
            <select class="container" id="school" name="school" style="width:100%; height:30px;">
                <option value="empty"> </option>
              <option value="Alabama A&M University">Alabama A&M University</option>
              <option value="Alabama State University">Alabama State University</option>
              <option value="Albany State University">Albany State University</option>
              <option value="Alcorn State University">Alcorn State University</option>
              <option value="Allen University">Allen University</option>
              <option value="American Baptist College">American Baptist College</option>
              <option value="Arkansas at Pine Bluff, University of">Arkansas at Pine Bluff, University of</option>
              <option value="Arkansas Baptist College">Arkansas Baptist College</option>
              <option value="Barber-Scotia College">Barber-Scotia College</option>
              <option value="Benedict College">Benedict College</option>
              <option value="Bennett College">Bennett College</option>
              <option value="Bethune-Cookman University">Bethune-Cookman University</option>
              <option value="Bishop State Community College">Bishop State Community College</option>
              <option value="Bluefield State College">Bluefield State College</option>
              <option value="Bowie State University">Bowie State University</option>
              <option value="Carver College ">Carver College </option>
              <option value="Central State University">Central State University</option>
              <option value="Cheyney University of Pennsylvania">Cheyney University of Pennsylvania </option>
              <option value="Claflin University">Claflin University</option>
              <option value="Clark Atlanta University">Clark Atlanta University</option>
              <option value="Clinton College">Clinton College</option>
              <option value="Coahoma Community College">Coahoma Community College</option>
              <option value="Coppin State University">Coppin State University</option>
              <option value="Delaware State University">Delaware State University</option>
              <option value="Denmark Technical College">Denmark Technical College</option>
              <option value="Dillard University">Dillard University</option>
              <option value="District of Columbia, University of the">District of Columbia, University of the</option>
              <option value="Edward Waters University">Edward Waters University</option>
              <option value="Elizabeth City State University">Elizabeth City State University</option>
              <option value="asu">Alabama State University</option>
              <option value="tsu">Texas Southern University</option>
              <option value="hamptonU">Hampton University</option>
              <option value="ssu">Savannah State University</option>
              <option value="ncat">North Carolina Agricultural and Technical State University</option>
              <option value="famu">Florida Agricultural and Mechanical University</option>
              <option value="wssu">Winston-Salem State University</option>
              <option value="vsu">Virginia State University</option>
              <option value="jcsu">Johnson C. Smith University</option>
              <option value="howardU">Howard University</option>
              <option value="dsu">Delaware State University</option>
              <option value="asu">Alabama State University</option>
              <option value="tsu">Texas Southern University</option>
              <option value="hamptonU">Hampton University</option>
              <option value="ssu">Savannah State University</option>
              <option value="ncat">North Carolina Agricultural and Technical State University</option>
              <option value="famu">Florida Agricultural and Mechanical University</option>
              <option value="wssu">Winston-Salem State University</option>
              <option value="vsu">Virginia State University</option>
              <option value="jcsu">Johnson C. Smith University</option>
              <option value="howardU">Howard University</option>
              <option value="dsu">Delaware State University</option>
              <option value="asu">Alabama State University</option>
              <option value="tsu">Texas Southern University</option>
              <option value="hamptonU">Hampton University</option>
              <option value="ssu">Savannah State University</option>
              <option value="ncat">North Carolina Agricultural and Technical State University</option>
              <option value="famu">Florida Agricultural and Mechanical University</option>
              <option value="wssu">Winston-Salem State University</option>
              <option value="vsu">Virginia State University</option>
              <option value="jcsu">Johnson C. Smith University</option>
              <option value="howardU">Howard University</option>
              <option value="dsu">Delaware State University</option>
              <option value="asu">Alabama State University</option>
              <option value="tsu">Texas Southern University</option>
              <option value="hamptonU">Hampton University</option>
              <option value="ssu">Savannah State University</option>
              <option value="ncat">North Carolina Agricultural and Technical State University</option>
              <option value="famu">Florida Agricultural and Mechanical University</option>
              <option value="wssu">Winston-Salem State University</option>
              <option value="vsu">Virginia State University</option>
              <option value="jcsu">Johnson C. Smith University</option>
              <option value="howardU">Howard University</option>
              <option value="dsu">Delaware State University</option>
              <option value="asu">Alabama State University</option>
              <option value="tsu">Texas Southern University</option>
              <option value="hamptonU">Hampton University</option>
              <option value="ssu">Savannah State University</option>
              <option value="ncat">North Carolina Agricultural and Technical State University</option>
              <option value="famu">Florida Agricultural and Mechanical University</option>
              <option value="wssu">Winston-Salem State University</option>
              <option value="vsu">Virginia State University</option>
              <option value="jcsu">Johnson C. Smith University</option>
              <option value="howardU">Howard University</option>
              <option value="dsu">Delaware State University</option>
              <option value="asu">Alabama State University</option>
              <option value="tsu">Texas Southern University</option>
              <option value="hamptonU">Hampton University</option>
              <option value="ssu">Savannah State University</option>
              <option value="ncat">North Carolina Agricultural and Technical State University</option>
              <option value="famu">Florida Agricultural and Mechanical University</option>
              <option value="wssu">Winston-Salem State University</option>
              <option value="vsu">Virginia State University</option>
              <option value="jcsu">Johnson C. Smith University</option>
              <option value="howardU">Howard University</option>
              <option value="dsu">Delaware State University</option>
              <option value="asu">Alabama State University</option>
              <option value="tsu">Texas Southern University</option>
              <option value="hamptonU">Hampton University</option>
              <option value="ssu">Savannah State University</option>
              <option value="ncat">North Carolina Agricultural and Technical State University</option>
              <option value="famu">Florida Agricultural and Mechanical University</option>
              <option value="wssu">Winston-Salem State University</option>
              <option value="vsu">Virginia State University</option>
              <option value="jcsu">Johnson C. Smith University</option>
              <option value="howardU">Howard University</option>
              <option value="dsu">Delaware State University</option>
              <option value="asu">Alabama State University</option>
              <option value="tsu">Texas Southern University</option>
              <option value="hamptonU">Hampton University</option>
              <option value="ssu">Savannah State University</option>
            </select></p>
<hr>