<p><label for="school_name">Select the HBCU you attend(ed):</label>
           
            <select class="container" id="school_name" name="school_name" style="width:100%; height:30px;">
                <option value="empty"> </option>
              <option value="Alabama A&M University">Alabama A&M University</option>
              <option value="Alabama State University">Alabama State University</option>
              <option value="Albany State University">Albany State University</option>
              <option value="Alcorn State University">Alcorn State University</option>
              <option value="Allen University">Allen University</option>
              <option value="American Baptist College">American Baptist College</option>
              <option value="Arkansas at Pine Bluff, University of">Arkansas at Pine Bluff, University of</option>
              <option value="Arkansas Baptist College">Arkansas Baptist College</option>
              <option value="Barber-Scotia College">Barber-Scotia College</option>
              <option value="Benedict College">Benedict College</option>
              <option value="Bennett College">Bennett College</option>
              <option value="Bethune-Cookman University">Bethune-Cookman University</option>
              <option value="Bishop State Community College">Bishop State Community College</option>
              <option value="Bluefield State College">Bluefield State College</option>
              <option value="Bowie State University">Bowie State University</option>
              <option value="Carver College ">Carver College </option>
              <option value="Central State University">Central State University</option>
              <option value="Cheyney University of Pennsylvania">Cheyney University of Pennsylvania </option>
              <option value="Claflin University">Claflin University</option>
              <option value="Clark Atlanta University">Clark Atlanta University</option>
              <option value="Clinton College">Clinton College</option>
              <option value="Coahoma Community College">Coahoma Community College</option>
              <option value="Coppin State University">Coppin State University</option>
              <option value="Delaware State University">Delaware State University</option>
              <option value="Denmark Technical College">Denmark Technical College</option>
              <option value="Dillard University">Dillard University</option>
              <option value="District of Columbia, University of the">District of Columbia, University of the</option>
              <option value="Edward Waters University">Edward Waters University</option>
              <option value="Elizabeth City State University">Elizabeth City State University</option>
              <option value="Fayetteville State University">Fayetteville State University</option>
              <option value="Fisk University">Fisk University</option>
              <option value="Florida A&M University">Florida A&M University</option>
              <option value="Florida Memorial University">Florida Memorial University</option>
              <option value="Fort Valley State University">Fort Valley State University</option>
              <option value="Grambling State University">Grambling State University</option>
              <option value="Hampton University">Hampton University</option>
              <option value="Harris-Stowe State University">Harris-Stowe State University</option>
              <option value="Howard University">Howard University</option>
              <option value="Huston-Tillotson University">Huston-Tillotson University</option>
              <option value="J. F. Drake State Technical College">J. F. Drake State Technical College</option>
              <option value="Jackson State University">Jackson State University</option>
              <option value="Jarvis Christian College">Jarvis Christian College</option>
              <option value="Johnson C. Smith University">Johnson C. Smith University</option>
              <option value="Kentucky State University">Kentucky State University</option>
              <option value="Lane College">Lane College</option>
              <option value="Langston University">Langston University</option>
              <option value="Lawson State Community College">Lawson State Community College</option>
              <option value="LeMoyne-Owen College">LeMoyne-Owen College</option>
              <option value="Lincoln University">Lincoln University</option>
              <option value="Livingstone College">Livingstone College</option>
              <option value="Maryland Eastern Shore, University of">Maryland Eastern Shore, University of</option>
              <option value="Meharry Medical College">Meharry Medical College</option>
              <option value="Miles College">Miles College</option>
              <option value="Mississippi Valley State University">Mississippi Valley State University</option>
              <option value="Morehouse College">Morehouse College</option>
              <option value="Morgan State University">Morgan State University</option>
              <option value="Morris Brown College">Morris Brown College</option>
              <option value="Norfolk State University">Norfolk State University</option>
              <option value="North Carolina A&T State University">North Carolina A&T State University</option>
              <option value="North Carolina Central University">North Carolina Central University</option>
              <option value="Oakwood University">Oakwood University</option>
              <option value="Paine College">Paine College</option>
              <option value="Paul Quinn College">Paul Quinn College</option>
              <option value="Philander Smith College">Philander Smith College</option>
              <option value="Prairie View A&M University">Prairie View A&M University</option>
              <option value="Rust College">Rust College</option>
              <option value="Savannah State University">Savannah State University</option>
              <option value="Selma University">Selma University</option>
              <option value="Shaw University">Shaw University</option>
              <option value="Shorter College ">Shorter College </option>
              <option value="Simmons College of Kentucky ">Simmons College of Kentucky </option>
              <option value="South Carolina State University">South Carolina State University</option>
              <option value="Southern University at New Orleans">Southern University at New Orleans</option>
              <option value="Southern University at Shreveport">Southern University at Shreveport</option>
              <option value="Southern University and A&M College">Southern University and A&M College</option>
              <option value="Southwestern Christian College">Southwestern Christian College</option>
              <option value="Spelman College">Spelman College</option>
              <option value="St. Augustine's University">St. Augustine's University</option>
              <option value="St. Philip's College">St. Philip's College</option>
              <option value="Stillman College">Stillman College</option>
              <option value="Talladega College">Talladega College</option>
              <option value="Tennessee State University">Tennessee State University</option>
              <option value="Texas College">Texas College</option>
              <option value="Texas Southern University">Texas Southern University</option>
              <option value="Tougaloo College">Tougaloo College</option>
              <option value="Tuskegee University">Tuskegee University</option>
              <option value="Virgin Islands, University of the">Virgin Islands, University of the</option>
              <option value="Virginia State University">Virginia State University</option>
              <option value="Virginia Union University">Virginia Union University</option>
              <option value="Virginia University of Lynchburg">Virginia University of Lynchburg</option>
              <option value="Voorhees University">Voorhees University</option>
              <option value="West Virginia State University">West Virginia State University</option>
              <option value="Wilberforce University">Wilberforce University</option>
              <option value="Wiley College">Wiley College</option>
              <option value="Winston-Salem State University">Winston-Salem State University</option>
              <option value="Xavier University of Louisiana">Xavier University of Louisiana</option>
              
            </select></p>
